#Workflow's name
name: "Build APK and IPA" 

#On github update
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - huylq19

#Actions      
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    env:
        XC_VERSION: ${{ '12.5.1' }}
        XC_SCHEME: ${{ 'dev' }}
        XC_CONFIGURATION: ${{ 'Automation' }}
        XC_WORKSPACE: ${{ 'Runner.xcworkspace' }}
        XC_ARCHIVE_PATH: ${{ './Runner.xcarchive' }}
        XC_EXPORT_PATH: ${{ './artifacts/' }}
        ENCRYPTED_CERTS_FILE_PATH: ${{ './ios/certs.p12.gpg' }}
        DECRYPTED_CERTS_FILE_PATH: ${{ './ios/certs.p12' }}
        ENCRYPTED_PROVISION_FILE_PATH: ${{ './ios/provisioning.tar.gz.gpg' }}
        DECRYPTED_PROVISION_FILE_PATH: ${{ './ios/provisioning.tar.gz' }}
        CERTS_ENCRYPTION_PWD: ${{ secrets.CRM_IOS_CERTIFICATE }}
        PROVISION_ENCRYPTION_PWD: ${{ secrets.CRM_IOS_CERTIFICATE }}
        CERTS_EXPORT_PWD: ${{ secrets.CERTS_EXPORT_PWD }}
        KEYCHAIN: ${{'KEYCHAIN'}}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '16.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.2'
      - run: flutter pub get

      - run:  flutter build apk --flavor dev -t ./lib/main_dev.dart --debug
      
      - name: Upload APK artifact 
        uses: actions/upload-artifact@v1
        with:
          name: app-dev-debug-apk
          path: build/app/outputs/flutter-apk/app-dev-debug.apk # Need to change path when change build command
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.CICD_CLONE }}

      # - run: |
      #     flutter build ios --flavor dev -t ./lib/main_dev.dart --debug
      #     cd build/ios/iphoneos
      #     mkdir Payload
      #     cd Payload
      #     ln -s ../Runner.app
      #     cd ..
      #     zip -r app.ipa Payload
      # artifacts: "build/app/outputs/apk/debug/app.apk,build/ios/iphoneos/app.ipa"

      - name: Select latest Xcode
        run: "sudo xcode-select -s /Applications/Xcode.app"
      - uses: actions/checkout@v1
      - name: Configure Keychain
        run:
          security list-keychains -s "$KEYCHAIN"
          security default-keychain -s "$KEYCHAIN"
          security unlock-keychain -p "" "$KEYCHAIN"  
          security set-keychain-settings
          security list-keychains
      - name: Configure Code Signing
        run:
          gpg -d -o "$DECRYPTED_CERTS_FILE_PATH" --pinentry-mode=loopback --passphrase "$CERTS_ENCRYPTION_PWD" "$ENCRYPTED_CERTS_FILE_PATH"
          gpg -d -o "$DECRYPTED_PROVISION_FILE_PATH" --pinentry-mode=loopback --passphrase "$PROVISION_ENCRYPTION_PWD" "$ENCRYPTED_PROVISION_FILE_PATH"
          security import "$DECRYPTED_CERTS_FILE_PATH" -k "$KEYCHAIN" -P "$CERTS_EXPORT_PWD" -A
          security set-key-partition-list -S apple-tool:,apple: -s -k "" "$KEYCHAIN"
          tar -xzvf "$DECRYPTED_PROVISION_FILE_PATH"
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          for PROVISION in `ls ./*.mobileprovision`
          do
            UUID=`/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< $(security cms -D -i ./$PROVISION)`
            cp "./$PROVISION" "$HOME/Library/MobileDevice/Provisioning Profiles/$UUID.mobileprovision"
          done
      - name: Archive
        run: |
          mkdir artifacts
          /usr/bin/xcodebuild archive -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -configuration "$XC_CONFIGURATION" -archivePath "$XC_ARCHIVE_PATH" "OTHER_CODE_SIGN_FLAGS=--keychain '$KEYCHAIN'"
      
      - name: Upload IPA artifact 
        uses: actions/upload-artifact@v1
        with:
          name: app-dev-debug-ipa
          path: build/ios/iphoneos/app.ipa # Need to change path when change build command
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.CICD_CLONE }}

          # https://zenn.dev/pressedkonbu/articles/254ca2fc3cd1ab