#Workflow's name
name: "Build APK and IPA" 

#On github update
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - huylq19

#Actions      
jobs:
  build_iOS:
    name: Build for iOS
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '16.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.2'
      - run: flutter pub get

      - name: Import Provisioning Profile
        run: mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo -n ${{ secrets.PROVISIONING_PROFILE }} | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/adhoc.mobileprovision

      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1 # 外部パッケージを使っている
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATE_PASSWORD }}

      # ipa ファイルの出力
      - name: Create ipa file
        # GITHUB_RUN_NUMBER をビルドナンバーに指定することで被りがないようにしている。
        run: flutter build ipa --build-number ${GITHUB_RUN_NUMBER}


      - name: Upload IPA artifact 
        uses: actions/upload-artifact@v1
        with:
          name: app-dev-debug-ipa
          path: build/ios/iphoneos/app.ipa # Need to change path when change build command
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.CICD_CLONE }}

          # https://zenn.dev/pressedkonbu/articles/254ca2fc3cd1ab
